version: 0.2

env:
  secrets-manager:
    DOCKER_USERNAME: dockerHub:username
    DOCKER_PASSWORD: dockerHub:password

phases:
  pre_build:
    commands:
      - echo Logging to Docker hub
      - docker login -p $DOCKER_PASSWORD -u DOCKER_USERNAME
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - docker build -f docker/Dockerfile -t $IMAGE_REPO_NAME:$IMAGE_TAG app/
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

# sample: https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html