---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Deployment pipeline"

Parameters:
  ProjectName:
    Type: String
    Default: "be-api-reco-mvp"
  BranchName:
    Type: String
    Description: "The deployment environment." 
    Default: "dev"
    AllowedValues:
      - "dev"
      - "uat"
      - "master"
  GitHubOwner:
    Type: String
    Description: "Owner of the github repo used for the source"
    Default: "wantedmedia"
  Repo:
    Type: String
    Description: "github repo used for the source"
    Default: "be-api-reco-mvp"
  GithubOAuthToken:
    Description: "The github OAUTH token to give codepipeline access to the gihub repo. To be provided when launching pipeline on the CLI - see https://docs.aws.amazon.com/codepipeline/latest/userguide/GitHub-create-personal-token-CLI.html" 
    Type: String
  NetworkingStackName:
    Type: String
    Description: "Name of the CF stack associated with the instrastrure codepipeline step within the be-awsInfra-networking project"
    Default: "be-awsInfra-networking-infra"
  EcsClusterStackName:
    Type: String
    Description: "Name of the CF stack associated with the instrastrure codepipeline step within the be-awsInfra-networking project"
    Default: "be-awsInfra-ecsCluster-infra"

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref ArtifactStoreS3Bucket
        Type: S3
      Name: !Sub "${ProjectName}-codePipeline-${BranchName}"
      RoleArn: !GetAtt CodePipelineRole.Arn
      RestartExecutionOnUpdate: true
      Stages:
        - Name: "Source"
          Actions:
            - Name: "SourceCode"
              Namespace: SourceVariables
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref Repo
                Branch: !Ref BranchName
                OAuthToken: !Ref GithubOAuthToken
                PollForSourceChanges: False
              OutputArtifacts:
                - Name: !Ref ProjectName
              RunOrder: 1
        - Name: "Deploy-Infrastructure-csv2ddb"
          Actions:
            - Name: "Deploy-Infrastructure-csv2ddb"
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: "CAPABILITY_NAMED_IAM"
                OutputFileName: InfrastructureOutput.json
                StackName: !Sub "${ProjectName}-infra-csv2ddb-${BranchName}"
                TemplatePath: !Sub "${ProjectName}::aws/01-infrastructure-csv2ddb.yml"
                RoleArn: !GetAtt DeployRole.Arn
                ParameterOverrides: !Sub |
                  {
                    "BranchName": "${BranchName}",
                    "ProjectName": "${ProjectName}"
                  }
              InputArtifacts:
                - Name: !Ref ProjectName
              OutputArtifacts:
                - Name: InfrastructureOutput
              RunOrder: 1
        - Name: "codeBuild-s3-upload"
          Actions:
            - Name: "codeBuild-s3-upload"
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Sub "${ProjectName}-build-s3-upload-${BranchName}"
                TemplatePath: !Sub "${ProjectName}::aws/02-build-s3-upload.yml"
                Capabilities: "CAPABILITY_NAMED_IAM"
                RoleArn: !GetAtt DeployRole.Arn
                ParameterOverrides: !Sub |
                  {
                    "ProjectName": "${ProjectName}",
                    "BranchName": "${BranchName}",
                    "BucketName": {
                      "Fn::GetParam": [
                        "InfrastructureOutput",
                        "InfrastructureOutput.json",
                        "BucketName"
                      ]
                    }
                  }
              InputArtifacts:
                - Name: !Ref ProjectName
                - Name: InfrastructureOutput
              RunOrder: 2
        - Name: "deploy-codeBuild-s3-upload"
          Actions:
            - Name: "deploy-codeBuild-s3-upload"
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Sub ${ProjectName}-build-s3-upload-${BranchName}
              InputArtifacts:
                - Name: !Ref ProjectName
              RunOrder: 3
        - Name: "CodeBuild-docker"
          Actions:
            - Name: "CodeBuild-docker"
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Sub "${ProjectName}-build-docker-${BranchName}"
                TemplatePath: !Sub "${ProjectName}::aws/03-build-docker.yml"
                Capabilities: "CAPABILITY_NAMED_IAM"
                RoleArn: !GetAtt DeployRole.Arn
                ParameterOverrides: !Sub |
                  {
                    "ProjectName": "${ProjectName}",
                    "ExecutionId": "#{codepipeline.PipelineExecutionId}",
                    "BranchName": "${BranchName}",
                    "EcsClusterStackName": "${EcsClusterStackName}"
                  }
              InputArtifacts:
                - Name: !Ref ProjectName
              RunOrder: 2
        - Name: "Deploy-CodeBuild-docker"
          Actions:
            - Name: "Deploy-CodeBuild-docker"
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Sub ${ProjectName}-build-docker-${BranchName}
              InputArtifacts:
                - Name: !Ref ProjectName
              RunOrder: 3
        - Name: "Deploy-Services"
          Actions:
            - Name: "Deploy-Services"
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Sub "${ProjectName}-services-${BranchName}"
                TemplatePath: !Sub "${ProjectName}::aws/04-services.yml"
                Capabilities: "CAPABILITY_NAMED_IAM"
                RoleArn: !GetAtt DeployRole.Arn
                ParameterOverrides: !Sub |
                  {
                    "ProjectName": "${ProjectName}",
                    "ExecutionId": "#{codepipeline.PipelineExecutionId}",
                    "BranchName": "${BranchName}",
                    "NetworkingStackName": "${NetworkingStackName}",
                    "EcsClusterStackName": "${EcsClusterStackName}"
                  }
              InputArtifacts:
                - Name: !Ref ProjectName
              RunOrder: 4

  PipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties: 
      Authentication: "GITHUB_HMAC"
      AuthenticationConfiguration:
        SecretToken: GithubOAuthToken
      Filters: 
        - JsonPath: "$.ref"
          MatchEquals: "refs/heads/{Branch}"
      Name: !Sub "${ProjectName}-githubWebhook-${BranchName}"
      RegisterWithThirdParty: true
      TargetAction: "SourceCode"
      TargetPipeline: !Ref CodePipeline
      TargetPipelineVersion: !GetAtt CodePipeline.Version

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: code-pipeline
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - cloudwatch:*
                  - cloudformation:*
                  - iam:PassRole
                  - codebuild:*
                Resource: "*"

  DeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  ArtifactStoreS3Bucket:
    Type: AWS::S3::Bucket